#!/bin/ruby
require 'pry'

gems = []
count = 0
# DATA.each_with_index do |line, i|
ARGF.each_with_index do |line, i|
  count = line.to_i if i == 0
  if i == 1
    gems = line.split('')
  else
    gems = line.split('').select {|g| gems.include?g and g =~ /[[:alpha:]]/ }.uniq
  end
  break if count == i
end
puts gems.size

__END__
100
xhsbaqwbokcaqbkhrzddydwirmldcr
kwkbkhlwmlpuomfaenahhnnpgqpkcxlspbomrweoqq
rtdckeukfoppbsiccflxqcoxrhwnxpwyjsrvjngqmbgqfwahhkzcbifrvpamffoxcetdochazcqsqhazndwdk
cakdnrducighyuuemxhqmujauwxabextkdamxybkoyexmdmlyvnmlrwwrt
czuzxlzrmuaa
gquymxuabmymtnljadbqxjsipnixbyhwhaoaciinwdhppbpyxswcveddpojlopqsuqsvjhpobpdefuj
abtwcqoib
vqpgcuwvxdlaquaiwydejgpwvpwdjeybgbtienzijzeah
shrcvpgwzdkfcvpmjeuslonwerklxysafwgeurdnshmzunpaxmgfiwsehowfyjboeahpuqlatcmooenlicnrkhcbkl
jcvcatdtubemfmjqfplxgwkqeuyderpznnqhvvpjafnceutugnixltiyrmnptcxpvqadnpowacsuoucwmfgbkzs
ufaqewahvnqsbpqw
jzecprvdbgyxmhslqdxjsqnmdoavvifebqrtklohndgvkemackgmgtpkhqetqybxnpiyvlebovhbwivctrruc
wrhighznjjppsvmsxmtwtnphaxqmyjwtxrrfqxrurbengtrvgmeaxfodwtfucmdeasgzuxkghhjexblancvzd
hluadkczkazvptpjwwempwfpacbnfmhrzghznjln
znizntdoqtqabqvykqvnglbgkmclrzajsqwxnshlzalzfbalkxoxpsmtoon
paws
nwtsbxdtyqlapasbazttbsguceyqjvebxdjnfdw
kxafenseotsysgeswrtpzibyamlhbjknlcoveihukdebfbwsaqmzvdlaytfilpcqkspdwnysdfjvwdtlsqactcrelzzhxqxzv
yqaaayknxwnbmzkictawsgxeq
aaqkpvmiiho
ybnnrikqjybxrawihgyxiegxcimriyqrrgcxsfeidnhwfxjnpzxhloav
pjpdtrolhxvfrftvuweatcisajvqkaqqmblwugegmbpteukwxvoebpemcjquuvlrqkczeabuhmss
epgmbfpdjktvkbiczmumnoirupbasdvxpjhsocxaewcxkquxjolcqwjwnqtnirgsi
hjvkyhlyuqrsoonfqlyxlenoszrlquqsyjwrufuretagpuq
oaqdya
ikqnbkmmaoxqjmrmxupfaycfwxwzeldjynafrjdkulsvqweciuyukxnmzriseziuqxoxif
jgabqaqhwashxvki
xrryvkqfkossukeieayukmycfusyrikiotoiutvykatijjjzrioys
uaepqfgaevkewfmyhdmfeifsheilwfusmlnrpjtaeathypaql
pkzqkqvlgadoatqdwhgwkehalzrfawkxlivimioralfsnwqyhampnhqhdgssoo
lyqmibiheakvntaijqiwviwadksmxewhzejpkhdlbisqxmaqcmxctkfvqo
zgylpetfogykwgypzyoxjcuglfcawxubtqnteyvajnafzznmojnhovohsaowhuqpwhlydmtzwvrirjknynsiijivpqguabg
eftqjvctdzhxqbupfkwppcsrujgrziuelxozbzzcrcfbghqzdftctzfxgvmevyvbdbfigsykevjanvlaoepmqedufn
aotiefuigarhpgsghcptscko
pfrqhzapxgeltxikswnocynfguafqsigbpwehbfywndxbxaupzbdggshjocvowitjvunospmtzudcpl
yqzudnoqenlskxakuummlvkefmljvteacihzapaabuvjyjgodptyavvupptmvypvhnta
solabz
vxlaetxbklmxztfkozbzlolqr
wvcga
wahauykchejjiyikfwxzsbufdegpovkrbpampyuuhsaqzcnybbjzajjjrbszvbvdpyhbccwsjmnoztlejpffnzfytrdppsjrpvxx
cxkhanwweqhcjttjorgjocdfknajxbtbsucabin
oya
bznssnvxqvhhsqtmvluzmafqhftmorixkanbsixebrjqucgatepukzivhyhwxzfhgqztqtizkftvthyqjec
bbrjqukyipcnrhirhvcsmzgftpxtvehmfiizhorionzyhqdxodpaazjducjoqowtwzspfs
cnznakegiobpzqlzgyicllqwgrscxedu
hmofrxma
adh
oxa
bglhbygsyapztwrxjedcvpctvilcazozpralyodujolkixitrxwimazwnxmglwvkem
rgiyigzujasnsovsjjaqizcomxakticqyqdpdughlyuazpnfbmcgnveiemsybfdg
rioajgayihhagpcrj
zqgipdddjqxctpdzqiwzxwvxnwoxstodzcwgergfiiaizebhktlvrizzkomimalfbsxkduavkjxaoairfh
kgjdzysfkxmetkaoylyskcqlqtfzyayyyudxsknzxrcyujmwbnbkbtsfgitrrawfxzjthyfmgckgjqespdifqtpxjbgnvr
hiagaaeynarcvstegt
yadxdlavbxptwglaiayoowuogvvtgcfywluubqtkzrrhfxlovgef
hlypqfdiqlfnkllzouulioezroipxqdlsxwanwykvbcldhoetaeztgrootpjojcceuacwtzqagqamcvgfdednqczyvbtdx
zisguwmsaxhxuwjmhyfzuwiipggmwdouo
lbwzvwermrlvcmklemjkfrbljlnxrtizbyeikrgwjjptnzumttueabagmxizruareaeykxpblhrxcdyncqvpvcunwnfxzmpgys
prttjtiytlyyrultdkkpltjieolromizxwjfesyslnlxawtuxfiykdjobvoaeehfvxanlqzpkznggwkteeevlvsshvptayxvmttl
qgkpbaajagtvqiyiaodlrsikonhfwakpjdcbtalsxcjvbedvcempmvoeenrignubtaslxftwagdiobnevqzvqva
faedrfxkahlcgoilakrcyivijzutjlrdumyufckvt
vau
hbvbxfjzegevcqgaphablnsmlbsoeqmaioprbvtddsupvnqngwmxcpflvuafxpvd
brtfnusycjisbcphougpjdvauguelqkzipcuijeoy
ichepvyzntaev
zenwbsywgmpiutpzcjlaatkzmgobpxbcxmuxarykyoeqdx
lfluwbfavxkugqlwyxasngjzsdsyjpgeydajtolqsx
bhczkeeqzhzbartmeqpaqruysxjzaauoiqktopalvmdktikkldlrjllmcdpoygeiyukptponoihbsrrfvjfhoce
zap
ruiospjscgsufpnqkxkyykawjzwkczikahsyzauktafln
lreuxplanxvcqitroicfi
ohfaufeligmwtcsawktgxwtplivubrwmcjbqwgkcoxjyjwheidyqthgkoakhewhnwkvcatqpbwsqfkiqabjjonykglqwbswfyt
vocqooogtaicbhuaiupuipleufvdccabmfywoykochscytztchknyorlocfdntwwovefaq
xdmyaggpho
nscoqroxhdadpeuycosccvsnmtuugabmctqjeirzc
jhhlrbgojnrllgdewjvleyqdbfqvnjykfdjlxswwqeacczilgonlysaeqjghqpmwulkpupahsbbwihayahdfljjfgedri
mnfhtdoelgcismveynwpedfgqiosyjadntdewxlufoqorroevrcv
tzcetubjznmepihqloxfevhnyxhoytayxpkjvsgtmpkcimescblehhpgtbrngbwaufvjoqprgipwbahzkhjxfjxruqegcjgwgn
pvcuauizaozvhsbtwgxihosfgjazpahwkai
zsgkakcjezqvrqokvtgvecfgykwmvdpnapvjsuglckolshfiawxkogumzwiverjxpoyyuyhmopglvvfyuwa
rfywidpltzdddyrhorkbfanakjjbfyhs
liwgcigsdsyglkbefvbraoaexrprytclpvbwwpppouxbcmhpzswfkuhbkbzhymrceewbsdjsugwznmouri
epaotrdpredwowbjpafkswggzhhzigjcrkvlpbqgucvaprkskwilfmgzyqiijibzvteiujzjqeankernianranftzkoafyzrj
ntvvsjszkygncqfabnbajpmibfykwgyfaloozaoohtvnxclgsxjnlyvhvg
bpsbesgxuufgaxsmcyhbfgfmzcyaxwizbmoyecacp
mjootlmwwumapdrjmbhayptf
kbrna
xgooaibxlpjfotxwfgjtomwpjhmvjliubjavgjizaudpta
cclrtzxwjsybpazszlbhwewuqbathpvrstemsdfqxblzlgblgkdrvpwitgqykmduvyapqw
jsnpkdnmgpxgayihlblrxdpwqrctzvzoaylituwbiojtfuhfkpaggsbmqjaddmfjhaqpscyxpznwhlbxnp
afclnupiwlgqchkdahacm
ghibvbwuorvaubjkwphqghpzzqhgqhagzgsrtoouxefpckwvcndwlxjnpzzliqeeduqlezlayvdvzfstzpyomdyx
cabazene
iccteslmzahdvafdufaiactlgghsqqsayzalvyvfznwwiwgdshqrzgukgdqswm
va
evcmyciioxyggjpyeojrptzrfijszfargbtqjwyyseijzehgzlwhrresgbnpmzmasx
gadtslngjkipbhdzfeypofxqdycmornqzwjucxsslvjhrmewcljekmeqtjaimjmxasyfbpjhkvgugmwkjyylygswjehflhwxv
dpcazx
mqakmgqxwqmj
ombmwzjgntuvvhulglygpoqswngfedmdlywxqwjrpcyokultptfzmxpbflshggoycfaanaezburiqsphbzeqzbhkfykaemgsgu
